### ISSUE TITLE
us3 question items not loading

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#261]
The Questions, Constructs and doc view have stopped loading, it is caused by the question items no longer loading. It is only affecting us3, but I can't see an issue with the db.  Ideally I do not want to roll this back to yesterday, as I have added over 50 questions this morning.

**Comment by charlesdebarros** [comment]
I have taken a look at listing question_items from Heroku backend. It displays the items but obviously that does not replicate to the frontend. One of the first things that I noticed is that US3, and also US4, do not load, and that very probably is due to their large size. One thing that I also noticed is that the loading of question_items pretty much failins instantly, i.e., it returns a Status code: 500 (internal server error). 

Another thing that I immediately noticed is that the question_items, questions_grids and questions themselves still have a few issues with N+1 database loading, i.e., they run queries for every single item instead of caching then loading the data. I will take a look at those at some point.

**Comment by HayleyMills** [comment]
The issue is specific to us3. It previously loaded (as does us4) when the higher dyno is on.  I've attached the exported xml from 30/11/2018 1am before any of the changes were made . It might be worth comparing this to the xml after the changes were made, which seemed to have caused the problem. Although the exporter is meant to run nightly after edits have been made, the latest xml export is not available yet. 

[us3_29102018.txt](https://github.com/CLOSER-Cohorts/archivist/files/2533921/us3_29102018.txt)

**Comment by charlesdebarros** [comment]
Just as note, on the day US3 broke, there was "parent_id" missing issue on 
construct_id: 180365
label: c_DEMOGRAPHICS_iv
construct_type: CcCondition (23025)
parent_id: NULL
position: 4
branch: 0

It may or may not be related to the trebled code issue.

**Comment by HayleyMills** [comment]
The latest export from 30th October (document 4169) was imported into Archivist (us3_rescued). This mostly imported correctly apart from the instructions were no longer attached to the question items. These were then added into the database, by matching them up with the original broken us3 in the database. The 50 questions will have to be added manually again.
