### ISSUE TITLE
Clean XML exporter for Discovery

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#280]
The current exporter, exports all content in XML DDI format regardless if there are elements which are not used in constructs. This was needed when the XML was used as a back-up.

However, we require only XML elements which are being used by the control constructs to be exported to be added to Discovery. 

Categories and instructions can be orphaned when they are edited and only used once. 

See issues #270 #279  #277 #273 #182 #183

**Comment by charlesdebarros** [comment]
The urn should always be linked to the row in the Identifier table in the database. Unless updated or deleted, in which case it will be a new category.

TODO:
Test the urn export behaviour.

**Comment by spuddybike** [comment]
see #209

**Comment by charlesdebarros** [comment]
An example of an 'orphan' element can be seen in `'https://closer-archivist.herokuapp.com/instruments/closer_CDI.xml'`
Seaching for word `'Peekaboo'`, it can be noticed that caregory `ca-240008` is directly linked to question_item `qi_137752`.

<img width="759" alt="Screen Shot 2019-07-29 at 10 58 56" src="https://user-images.githubusercontent.com/6763090/62040286-31aa7480-b1f1-11e9-9906-9842b866b27e.png">

<img width="671" alt="Screen Shot 2019-07-29 at 10 59 17" src="https://user-images.githubusercontent.com/6763090/62040276-2ce5c080-b1f1-11e9-9daf-b2908a677dca.png">

On the other hand, caregory `ca-214539` is not liked to any question_item. `ca-214539` was the original item that, once modified, became orphan as a new category was created with a link to the original question_item. 

<img width="711" alt="Screen Shot 2019-07-29 at 10 57 27" src="https://user-images.githubusercontent.com/6763090/62040309-3e2ecd00-b1f1-11e9-82c6-02bb3a9c1e2b.png">

I believe this happens because, instead of writing the changes to the original category, Archivist creates a new caterogy with the changes - and does not get rid of the old category.

**Comment by charlesdebarros** [comment]
This instrument was failing to be imported because of an self-closing, empty Category label - category_id -> 213833. 

<l:Category>
<r:URN>urn:ddi:uk.closer:closer_CDI-ca-213833:1.0.0</r:URN>
<l:CategoryName>
<r:String xml:lang="en-GB">213833</r:String>
</l:CategoryName>
<r:Label>
**_<r:Content xml:lang="en-GB"/>_**
</r:Label>
</l:Category>

**Comment by spuddybike** [comment]
see #183 which could usefully be picked up ehre

**Comment by HayleyMills** [comment]
Thanks I'll test when the issues from Browser 1: have been resolved.

**Comment by HayleyMills** [comment]
Tested on staging for instruments which didn't have nils in rds_qs rd_order to circumvent the issues which may be caused by #306 
First test was to export and then import an instrument then re-export to see if there was any difference between the XML. 

Tested by exporting closer_CDI which had a known orphaned category. I changed the prefix to closer_CDI_import and then imported back in. This instrument didn't load correctly- it is stuck on categories.

Tested with alspac_99_ttd to make sure that Archivist was loading for an instrument without orphaned categories. Changed the prefix to closer_CDI_import and then imported back in. This did load correctly. I then exported this and I diffed the two XML files. I found differences in the version date, the URNs and the CategoryName. 

Tested another instrument with orphaned categories alspac_00_mhmfam, and this didn't load correctly- it is also stuck on categories.

**Comment by simonreed** [comment]
Hi @HayleyMills are you importing through https://closer-archivist-staging.herokuapp.com/admin/import and exporting through https://closer-archivist-staging.herokuapp.com/admin/export?

The reason I ask is that I can't import using an export produced by the above links as when you import from there it creates a new Instrument with the prefix derived from the URN in the export XML. This export URN obviously uses the prefix from the original instrument so the import will fail. Have you changed the name of the URNs in the XML you're then importing? Can you tell me what you're doing to replicate this on staging?



> Tested on staging for instruments which didn't have nils in rds_qs rd_order to circumvent the issues which may be caused by #306
> First test was to export and then import an instrument then re-export to see if there was any difference between the XML.
> 
> Tested by exporting closer_CDI which had a known orphaned category. I changed the prefix to closer_CDI_import and then imported back in. This instrument didn't load correctly- it is stuck on categories.
> 
> Tested with alspac_99_ttd to make sure that Archivist was loading for an instrument without orphaned categories. Changed the prefix to closer_CDI_import and then imported back in. This did load correctly. I then exported this and I diffed the two XML files. I found differences in the version date, the URNs and the CategoryName.

The URN will be different from the import to the export as the URN contains the db id for the records, which will be different if you export from one instrument and then import into another instrument. The prefix will also be different. The version date will also be different as that is the timestamp for when the export was generated, which will be different to if you import to another instrument and then export again.

Could you give me a link to the XML which is different for the category names?

**Comment by HayleyMills** [comment]
@simonreed Yes I've been exporting and importing as you said. I have changed the prefix within the files in order to import them as they would be duplicates. 

The different URNS, date and prefix all make sense thanks. I'm more unclear about what the CategoryName was?
https://closer-archivist-staging.herokuapp.com/instruments/1122/export/4706
https://closer-archivist-staging.herokuapp.com/instruments/1698/export/4741

**Comment by simonreed** [comment]
re: categories

4741.xml has
```
      <l:Category>
        <r:URN>urn:ddi:uk.alspac:alspac_99_ttd_import-ca-247395:1.0.0</r:URN>
        <l:CategoryName>
          <r:String xml:lang="en-GB">247395</r:String>
        </l:CategoryName>
        <r:Label>
          <r:Content xml:lang="en-GB">yes, I had one once</r:Content>
        </r:Label>
      </l:Category>
```

while 4706.xml has 
```
      <l:Category>
        <r:URN>urn:ddi:uk.alspac:alspac_99_ttd-ca-156518:1.0.0</r:URN>
        <l:CategoryName>
          <r:String xml:lang="en-GB">156518</r:String>
        </l:CategoryName>
        <r:Label>
          <r:Content xml:lang="en-GB">yes, I had one once</r:Content>
        </r:Label>
      </l:Category>
```

The difference being:

*  the URN. Which was explained here https://github.com/CLOSER-Cohorts/archivist/issues/280#issuecomment-520876860
* The r:String. Which is just the db ID of the category, this is again going to be different when you import them as they're new db records.

**Comment by HayleyMills** [comment]
Thanks Simon, so the category name is simply the ID in the record. This makes sense. 
Any ideas why the other two instruments are not loading?

**Comment by simonreed** [comment]
@HayleyMills the export was not making sure that the Category entry was unique, which meant that the import was failing as it was trying to add duplicate categories. The pull request here https://github.com/CLOSER-Cohorts/archivist/pull/310 addresses this issue so that any QuestionItem, QuestionGrid, CodeList, Category is unique in the export XML.

This whole issue does raise a wider issue that too much of the import work is hidden from view. I'd suggest that we record and `Import` as a record in the DB so that the users can see the status of the import and any error messages within the UI.

**Comment by spuddybike** [comment]
@simonreed Yes, it is good idea to record the status and error message. I'll add a new issue

**Comment by HayleyMills** [comment]
Tested on staging by re-exporting closer_CDI. I changed the prefix to closer_CDI_import_14th and re-imported. It looks like it imported as the construct count on the instrument page is 50 as expected, but none of the pages are loading? 

I've attach the XML I imported, in case there is something I did wrong with it. I changed the ext. to .txt so it would attach. 
[closer_CDI_import_14th.txt](https://github.com/CLOSER-Cohorts/archivist/files/3502006/closer_CDI_import_14th.txt)

**Comment by HayleyMills** [comment]
Importer issues? #311 
@simonreed Tested on staging by re-exporting closer_CDI. I changed the prefix to closer_CDI_import_14th and re-imported. It looks like it imported as the construct count on the instrument page is 50 as expected, but none of the pages are loading? 

alspac_02_qht and re-imported alspac_02_qht_import- There are some differences in the instruments for example: instructions are missing, some questions do not have response domains attached, as the response domains have not been imported, cardinality has defaulted to 1-1. T

**Comment by HayleyMills** [comment]
The clean exporter issue can be signed off as tested. Backups will be made and broken instruments restored using the DB rather than the exports. 

Outstanding issues related to how categories and instructions are updated. I have reopened #279

**Comment by HayleyMills** [comment]
It looks like the exporter is no longer populating the identifiers table? I have tested on staging and onsls versions of Archivist.

**Comment by HayleyMills** [comment]
I think the identifiers table is populated when an instrument it imported? Is that correct and what is is used for? @simonreed
