### ISSUE TITLE
App falls over on startup

### ISSUE THREAD

**Issue by spuddybike** [CLOSER-Cohorts/archivist#478]
I've added you to the instance as collaborator - this is the log when you start up the app
[Syslog-drain_2020-12-15_105441_2020-12-15_111441.log.gz](https://github.com/CLOSER-Cohorts/archivist/files/5695387/Syslog-drain_2020-12-15_105441_2020-12-15_111441.log.gz)

**Comment by simonreed** [comment]
It's failing because it doesn't have a database running. Can set the DB level on this heroku instance to match the other staging environments. Can we also do the same with closer-react, @spuddybike I've changed the ownership of closer-react back to closerserver2@ucl.ac.uk so that the upgraded paid DB level can be billed to UCL directly. 

Once they have the new DB level then we should be able to copy the database from the staging instance over to closer-temp and closer-react.

**Comment by spuddybike** [comment]
thank you, I'll do that and let you know once its up

> It's failing because it doesn't have a database running. Can set the DB level on this heroku instance to match the other staging environments. Can we also do the same with closer-react, @spuddybike I've changed the ownership of closer-react back to [closerserver2@ucl.ac.uk](mailto:closerserver2@ucl.ac.uk) so that the upgraded paid DB level can be billed to UCL directly.
> 
> Once they have the new DB level then we should be able to copy the database from the staging instance over to closer-temp and closer-react.

@jli755

**Comment by simonreed** [comment]
Thanks @spuddybike could you add me as a collaborator on closer-react when you get a chance. When I moved ownership it removed my access to it.

**Comment by simonreed** [comment]
@spuddybike It appears I don't have permissions in heroku to migrate a database can you run `heroku pg:copy closer-staging::DATABASE_URL DATABASE_URL --app closer-temp` and `heroku pg:copy closer-staging::DATABASE_URL DATABASE_URL --app closer-react` as the owner of those applications.
