### ISSUE TITLE
REACT: Ability to copy and paste from the doc view

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#549]
We need to be able to copy and paste from the doc view in order to then find items in the construct view or to copy and paste into text to speech software.

**Comment by simonreed** [comment]
You can now copy and paste the text from an instrument doc view. The compromise for that is that you now need to click on the up/down arrow to expand/contract a sequence etc instead of just clicking anywhere on the sequence name.

<img width="1258" alt="Screenshot 2021-03-17 at 21 20 45" src="https://user-images.githubusercontent.com/13276/111540128-a59ee500-8766-11eb-97ea-451e3ff7ed63.png">

This is now on heroku-react

**Comment by HayleyMills** [comment]
Tested and this works well.
