### ISSUE TITLE
REACT: download .txt file buttons

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#684]
We could add the download cc_questions.txt, qv.txt and tq.txt, mapper.txt buttons to the https://closer-archivist-staging.herokuapp.com/admin/instruments/exports page?

If we want to do the same for the datasets, we would need a new page for dataset exports for variables.txt, tv.txt and dv.txt. 

I think this makes more sense then having the buttons on the individual instrument/dataset pages. 

Is it then possible to add a download all, so it downloads all the txt files and the download exported xml (not complete) for each instrument/dataset (not all instruments). This is not essential, as we have a GitLab pipeline for this.

**Comment by simonreed** [comment]
@HayleyMills These screenshots are from my local version but this is now on staging.

In the Admin Instrument Exports page you now have a button to 'View' an instrument exports

<img width="1358" alt="Screenshot 2022-05-19 at 19 43 18" src="https://user-images.githubusercontent.com/13276/169376530-9b14fa44-6d75-4ab1-be72-1202619eecb6.png">

You are then shown a page for that instrument where you can easily see the txt files associated with that instrument as well as a list of the XML exports (so you can go back in time). It also lists the associated datasets for that instrument so that you can easily grab all the txt files in one place.

<img width="1579" alt="Screenshot 2022-05-19 at 19 38 11" src="https://user-images.githubusercontent.com/13276/169375743-369fe69f-1873-4621-9fe4-52ba92376027.png">

To make sure that you can still access the txt files for datasets that don't have an instrument associated with it, you can also 'View' a dataset from the Admin Dataset page.

<img width="862" alt="Screenshot 2022-05-19 at 19 39 14" src="https://user-images.githubusercontent.com/13276/169375906-0943e828-991e-4cac-8ef3-fa24d431226d.png">

<img width="1581" alt="Screenshot 2022-05-19 at 19 39 33" src="https://user-images.githubusercontent.com/13276/169375956-2cc3bc00-ae18-4ab7-ae99-e40c98b5d10a.png">

**Comment by HayleyMills** [comment]
This looks and is working great. I have feature request now that we have these addtional pages, it would be great to have the percentage of mappings compelte. I'll add this as a separate issue request for another time.
