### ISSUE TITLE
Variable topic assigned but also says resolved

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#858]
![image](https://github.com/CLOSER-Cohorts/archivist/assets/16664703/2f97ffd8-7bc0-4a2d-acaf-26872a6692fc)
 This was found on live and was corrected, so I will need to replicate on staging.

**Comment by simonreed** [comment]
@HayleyMills Which instance is this on? I've pulled down the main archivist and it's showing both the topic and resolved topic as 'Parenting'.

Am I right in thinking there's 3 problems here : 

1. The fact the topic and the resolved topic are different. Should there be an error message on this variable?
2. How did it get into this state where it has different topics.
3. If there's a topic set for a variable then we shouldn't show the resolved topic.

**Comment by HayleyMills** [comment]
It was on main. Yes exactly. It also looks okay for me now too. Do you want me to try and replicate on staging?

**Comment by simonreed** [comment]
yes please. I've got a fix for point 3 but point 1 and 2 aren't so clear.

**Comment by HayleyMills** [comment]
Loaded QV and TQ, then TV. 
https://closer-archivist-staging.herokuapp.com/datasets/802


[mcs2_tv.txt](https://github.com/user-attachments/files/16336823/mcs2_tv.txt)
[mcs2_qv.txt](https://github.com/user-attachments/files/16336824/mcs2_qv.txt)
[mcs2_tq.txt](https://github.com/user-attachments/files/16336825/mcs2_tq.txt)

**Comment by spuddybike** [comment]
also #830

**Comment by HayleyMills** [comment]
Tested on staging 
https://closer-archivist-staging.herokuapp.com/admin/datasets/805/imports/1344

![image](https://github.com/user-attachments/assets/fbefee9a-0ec8-4252-943d-cf93707b968f)

https://closer-archivist-staging.herokuapp.com/datasets/805
![image](https://github.com/user-attachments/assets/9620a0ea-7bd9-4ce0-a7c3-707dd3ec3bd2)

No conflict error is shown.

**Comment by simonreed** [comment]
@HayleyMills this should be on staging now

**Comment by HayleyMills** [comment]
As above, the conflict variable topic is no longer assigned with the tv.txt as well as the already resolved/inherited topic from tq.txt which was loaded first, however there still should be a conflict error to show this. 

https://github.com/CLOSER-Cohorts/archivist/issues/858#issuecomment-2247925030

**Comment by simonreed** [comment]
The conflict was caught when importing the tv.txt so the topic wasn't assigned. The conflict is showing the import logs in your comment. 

Because the topic wasn't added due to the conflict on the import when you view the dataset there is no conflict to show as the topic wasn't persisted.

If you do however try to manually set the topic to 'Parenting' on https://closer-archivist-staging.herokuapp.com/datasets/805 it does show the conflict error.

<img width="1462" alt="Screenshot 2024-07-29 at 09 38 50" src="https://github.com/user-attachments/assets/fdd19637-da60-4863-93c7-70dcde144a0a">

The conflict is shown in the imports when the conflict is caught as part of the import and shown on the dataset page if attempting to conflict manually.

**Comment by HayleyMills** [comment]
Ok, I will make a note of this in the documentation, so we know this is the behaviour.
